### ISSUE TITLE
Adding an rpc.proto example for demo purpose

### ISSUE THREAD

**Issue by tlkahn** [sangaman/lightninggem#1]
Can anyone add a `rpc.proto`, just to fully illustrate how the grpc work with lightining network? It is currently in `.gitignore` now. Thanks so much.

**Comment by sangaman** [comment]
Very sorry I missed this earlier, just noticed it now. I'm using [this proto file](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/rpc.proto) with line 3 commented out. Let me know if this answers your question.

**Comment by sangaman** [comment]
Closing this issue, feel free to reopen or comment again if you have any more questions.
